# Generated by Django 3.0.3 on 2020-03-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='lastRead',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
