# Generated by Django 3.0.3 on 2020-03-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_join_lastread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='lastRead',
            new_name='last_read',
        ),
    ]
